### ISSUE TITLE
Quota limit

### ISSUE THREAD

**Issue by gorstj** [cyr-ius/hass-audiconnect#28] opened 2023-11-03 22:28 UTC
The integration works well for me for a day or so but then has major issues.

It breaks my officialAudi phone app

In the HA log I get

Unable to obtain the vehicle charger state for [VIN-DELETED]: (429, {'error': {'errorCode': 'gw.error.VINquotalimitReached', 'description': 'Global quota limit by VIN was reached'}})

It seems that the (unofficial API) has a limit we are breaching.

If I disable the integration for a day the Audi app then works and if I re-enable the integration it also works for about a day.

Do we need an option/default to reduce the polling interval?

**Comment by tieskuh** [comment] 2023-11-05 14:06
Duplicate of https://github.com/cyr-ius/hass-audiconnect/issues/25

**Comment by MatthewC105** [comment] 2023-11-22 17:32
I edited the file: **coordinator.py**, line 19.
From: **SCAN_INTERVAL = 5**
To: **SCAN_INTERVAL = 45**

This then updates every 45 mins, which seems to have not hit the API limit so far.

**Closed** 2024-01-04 12:39 UTC
